### ISSUE TITLE
PA Review: User Auth #2 

### ISSUE THREAD

**Issue by drewrodrigues** [thesimpledev/agile_tracker#2]
- [x]  Users can sign up
- [x]  Users can sign in
- [x]  Users can sign out
- [x]  Users can use a demo login to test the app
- [x]  Adequate styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds to demonstrate the feature

**Comment by drewrodrigues** [comment]
Fixed the icons 👯  @ryan-mapa

**Comment by ryan-mapa** [comment]
Lookin slick!
