### ISSUE TITLE
PA Review: Story Workflow #5

### ISSUE THREAD

**Issue by drewrodrigues** [thesimpledev/agile_tracker#4]
>##### Logged in users can...
###### when story `unstarted`
- [x] click `start` button on a story to change its status to `started`
###### when story `started`
- [x] click `finish` button to change its status to `finished`
###### when story `finished`
- [x] click `deliver` to change its status to `delivered`
###### when story `delivered`
- [x] click `accept` or `reject` to change its status to one of the two
###### when story `rejected`
- [x] click `restart` to change its status back to `started`

**Comment by ryan-mapa** [comment]
There's a lot going on here. It looks done though?

**Comment by ryan-mapa** [comment]
Looks great!
